import type { Project, Task, StatusConfig } from '../types'
import { sanitizeFileName, isTerminalStatus } from '../utils'
import { appendYaml, stripAutoGeneratedContent, FRONTMATTER_KEY, TASK_FRONTMATTER_KEY } from './YamlParser'

// ─── Serialize ──────────────────────────────────────────────────────────────

export function serializeProject(project: Project, statuses: StatusConfig[] = []): string {
  const seen = new Set<string>()
  const tasks: Task[] = []
  for (const t of project.tasks) {
    if (seen.has(t.id)) continue
    seen.add(t.id)
    tasks.push(t)
  }
  const taskIds = tasks.map((t) => t.id)

  const fm: Record<string, unknown> = {
    [FRONTMATTER_KEY]: true,
    id: project.id,
    title: project.title,
    description: project.description,
    color: project.color,
    icon: project.icon,
    taskIds,
    customFields: project.customFields,
    teamMembers: project.teamMembers,
    savedViews: project.savedViews.length ? project.savedViews : [],
    createdAt: project.createdAt,
    updatedAt: project.updatedAt
  }

  const yamlLines: string[] = ['---']
  appendYaml(yamlLines, fm, 0)
  yamlLines.push('---')
  yamlLines.push('')
  yamlLines.push(`# ${project.icon} ${project.title}`)
  yamlLines.push('')
  if (project.description) {
    yamlLines.push(project.description)
    yamlLines.push('')
  }
  if (tasks.length) {
    yamlLines.push('## Tasks')
    for (const t of tasks) {
      if (t.filePath) {
        const basename = t.filePath.replace(/^.*\//, '').replace(/\.md$/, '')
        const check = isTerminalStatus(t.status, statuses) ? 'x' : ' '
        yamlLines.push(`- [${check}] [[${basename}|${t.title}]]`)
      }
    }
    yamlLines.push('')
  }

  return yamlLines.join('\n')
}

export function serializeTask(
  task: Task,
  project: Project,
  parentTask: Task | null,
  statuses: StatusConfig[] = []
): string {
  const subtaskIds = task.subtasks.map((s) => s.id)
  const fm: Record<string, unknown> = {
    [TASK_FRONTMATTER_KEY]: true,
    projectId: project.id,
    parentId: parentTask?.id ?? null,
    id: task.id,
    title: task.title,
    type: task.type,
    status: task.status,
    priority: task.priority,
    start: task.start,
    due: task.due,
    progress: task.progress,
    assignees: task.assignees,
    tags: task.tags,
    subtaskIds,
    dependencies: task.dependencies,
    collapsed: task.collapsed,
    createdAt: task.createdAt,
    updatedAt: task.updatedAt
  }
  if (task.recurrence) fm.recurrence = task.recurrence
  if (task.timeEstimate !== undefined) fm.timeEstimate = task.timeEstimate
  if (task.timeLogs?.length) fm.timeLogs = task.timeLogs
  if (Object.keys(task.customFields).length) fm.customFields = task.customFields

  const yamlLines: string[] = ['---']
  appendYaml(yamlLines, fm, 0)
  yamlLines.push('---')
  yamlLines.push('')
  const cleanDesc = stripAutoGeneratedContent(task.description)
  if (cleanDesc) {
    yamlLines.push(cleanDesc)
    yamlLines.push('')
  }

  if (parentTask?.filePath) {
    const parentBasename = parentTask.filePath.replace(/^.*\//, '').replace(/\.md$/, '')
    yamlLines.push(`Parent: [[${parentBasename}|${parentTask.title}]]`)
  } else {
    const projectBasename = project.filePath.replace(/^.*\//, '').replace(/\.md$/, '')
    yamlLines.push(`Project: [[${projectBasename}|${project.title}]]`)
  }

  if (task.subtasks.length) {
    yamlLines.push('')
    yamlLines.push('## Subtasks')
    for (const sub of task.subtasks) {
      const subBasename = sub.filePath ? sub.filePath.replace(/^.*\//, '').replace(/\.md$/, '') : taskSlug(sub.title)
      const check = isTerminalStatus(sub.status, statuses) ? 'x' : ' '
      yamlLines.push(`- [${check}] [[${subBasename}|${sub.title}]]`)
    }
  }

  return yamlLines.join('\n')
}

function taskSlug(title: string): string {
  return sanitizeFileName(title).toLowerCase().replace(/\s+/g, '-').slice(0, 40)
}

/** Build the file path for a task .md file */
export function taskFilePath(taskTitle: string, folder: string): string {
  return `${folder}/${taskSlug(taskTitle)}.md`
}
